[1.20.0] Airgapped updates using CLI
replicatedhq/kots.io pull request #301
Opened 2020-10-07 17:35 UTC by divolgin

2020-10-07 17:55 UTC, marccampbell requested changes

2020-10-07 17:55 UTC, marccampbell commented on content/kotsadm/installing/installing-embedded-cluster.md
> +Note that the airgapped installer in the above step is not the application installer.  After this command completes, the application can be installed using the application airgap bundle.
@codelingobot capture Separate sentences with a linebreak in markdown files.

2020-10-07 17:55 UTC, marccampbell commented on content/kotsadm/updating/updating-kots-apps.md
> +To manually check for a more recent version, click the "Check for updates" button at the top of the admin console.
@codelinegobot capture "admin console" should be capitalized as "Admin Console"

2020-10-07 22:17 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +This article refers to installing the Admin Console on an embedded cluster.
Not sure if this is better, but I feel like we should clarify that this creates a cluster with admin console, not installs admin console into a cluster.

```suggestion
This article refers to installing the Admin Console with an embedded cluster.
```

2020-10-07 22:17 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +This article refers to installing the Admin Console on an embedded cluster.
Maybe "along with..."

2020-10-07 22:20 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +Note that the airgapped installer in the above step is not the application installer.  After this command completes, the application can be installed using the application airgap bundle.
This can be clearer. If it's not the application installer, what is it? Does it have a name?

2020-10-07 22:27 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +Note that the airgapped installer in the above step is not the application installer.  After this command completes, the application can be installed using the application airgap bundle.
Maybe we need a meta section that clarifies that installing an app to an embedded cluster is a two-step process. First create the cluster with Admin Console included, then start Admin Console and install the application.

2020-10-07 22:31 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +Note that the airgapped installer in the above step is not the application installer.  After this command completes, the application can be installed using the application airgap bundle.
Going further, Clarifying that there are two things to download might be important, given this is airgapped, and you need to download them both (plus the license) and *then* run the commands.

2020-10-07 22:33 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
>  ### Online Installations
So, the airgap instructions explain installing both admin console and the app, yet this section only covers admin console and gives no instruction for how to actually finish installing your app. Where are those instructions?

2020-10-07 22:37 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +Applications can also be installed into existing clusters as described in [this doc](/kotsadm/installing/airgap-packages/).
That's not a "doc". I don't like using "here", but it's slightly better.

```suggestion
Applications can also be installed into existing clusters as described [here](/kotsadm/installing/airgap-packages/).
```

2020-10-07 22:37 UTC, markpundsack commented on content/kotsadm/installing/installing-embedded-cluster.md
> +Applications can also be installed into existing clusters as described in [this doc](/kotsadm/installing/airgap-packages/).
Why do we even need to link out to this? This whole page is about embedded clusters. If we want to redirect folks looking for existing cluster installs, shouldn't that be at the top of the doc?

2020-10-07 22:40 UTC, markpundsack commented
Maybe we can go ahead and merge this because it's an improvement, but we have further improvement to do.

2020-10-08 15:22 UTC, marccampbell commented on content/kotsadm/updating/updating-kots-apps.md
> +The Admin Console automatically checks for updates once every 15 minutes.
@codelingobot capture "admin console" should be capitalized as "Admin Console"

2020-10-08 15:22 UTC, marccampbell commented on content/kotsadm/updating/updating-kots-apps.md
> +Admin Console CLI can be used to install and deploy updates for both online and airgapped instances as well.
This should be `The KOTS CLI`, it's not the Admin Console CLI?

2020-10-08 21:30 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
> +Admin Console CLI can be used to install and deploy updates for both online and airgapped instances as well.
```suggestion
The Kots CLI can be used to deploy updates for both online and airgapped instances.
```

2020-10-08 22:12 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
> +In airgapped instances this button will be replaced with a `Upload a new version` button.
```suggestion
In airgapped instances this button will be replaced with an `Upload a new version` button.
```

2020-10-08 22:13 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
>  When an update is available, a new upstream version will show in the list of released versions.
This is weird in this order. Sounds like "when an update is available" is directly related to airgapped instances.

2020-10-09 01:11 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
>  ![New Version Available](/images/new-version-available.png)
```suggestion
[![New Version Available](/images/new-version-available.png)](/images/new-version-available.png)
```

2020-10-09 01:11 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
>  ![New Changes](/images/new-changes.png)
```suggestion
[![New Changes](/images/new-changes.png)](/images/new-changes.png)
```

2020-10-09 01:11 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
>  ![Diff Releases](/images/diff-releases.png)
```suggestion
[![Diff Releases](/images/diff-releases.png)](/images/diff-releases.png)
```

2020-10-09 01:11 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
>  ![Preflight Checks](/images/preflight-checks.png)
```suggestion
[![Preflight Checks](/images/preflight-checks.png)](/images/preflight-checks.png)
```

2020-10-09 01:11 UTC, markpundsack commented on content/kotsadm/updating/updating-kots-apps.md
>  ![Updated Version](/images/version-history.png)
```suggestion
[![Updated Version](/images/version-history.png)](/images/version-history.png)
```

2020-10-10 01:45 UTC, merged