Release notes 1.33.0
replicatedhq/kots.io pull request #425
Opened 2021-03-05 18:33 UTC by jgruica

2021-03-05 19:13 UTC, GraysonNull requested changes

2021-03-05 19:13 UTC, GraysonNull commented on content/release-notes/1.33.0.md
> +* Show correct page title while on the [Cluster Management](/vendor/guides/ha-guide/#adding-remaining-nodes-to-cluster) page.
This should probably follow the "Fixed a bug..." format.

`Fixed a bug where the wrong page title was shown on the Cluster Management page`

2021-03-05 19:13 UTC, emosbaugh commented on content/release-notes/1.33.0.md
> +* Fixed a bug that caused documents getting ignored in the Helm file
```suggestion
* Fixed a bug that could cause documents to get ignored in Helm Charts
```

2021-03-05 23:27 UTC, AmberAlston approved these changes

2021-03-09 03:56 UTC, salahalsaleh approved these changes

2021-03-09 03:58 UTC, merged