Update private-images.md
replicatedhq/kots.io pull request #498
Opened 2021-06-10 18:01 UTC by jdewinne

2021-06-25 21:43 UTC, AmberAlston commented
@jdewinne is this still in-progress or ready for review? If ready for review, can you add a reviewer please?

2021-06-26 01:47 UTC, tdensmore approved these changes
LGTM. Thanks for adding the username/password and the token/token options.

2021-06-28 18:05 UTC, marccampbell commented on content/vendor/packaging/private-images.md
> +When building your application, you have the option to use the Replicated private registry, or any supported external private or public registry.
I think the second comma shouldn't be here.

2021-06-29 16:37 UTC, sgalsaleh approved these changes

2021-06-29 17:42 UTC, tdensmore commented on content/vendor/packaging/private-images.md
> +When using the Replicated Private Registry, you have 2 options to connect with the `registry.replicated.com` container registry
how about a colon after "registry"?

"When using the Replicated Private Registry, you have 2 options to connect with the `registry.replicated.com` container registry:"

2021-06-29 17:43 UTC, tdensmore requested changes
LGTM with the single suggestion

2021-06-29 19:30 UTC, merged