Tutorials
replicatedhq/kots.io pull request #547
Opened 2021-08-10 15:08 UTC by BarryWilliams

Adding initial drafts of vendor portal tutorials. These are built on-demand, so they are narrow subjects, but the goal is that the base of tutorials will grow and become comprehensive.

2021-08-20 14:07 UTC, tdensmore commented
@BarryWilliams I would love to see this published. Do you want to add reviewers to this for additional comments?

2021-11-08 14:01 UTC, dexhorthy commented
@BarryWilliams what's needed to get this merged?

2021-11-09 21:54 UTC, BarryWilliams commented
@replicatedhq/replicated-docs

2021-11-11 05:07 UTC, samantha-replicated requested changes

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +    In this example, We will add a resource which permits reading all members.
```suggestion
    In this example, a resource is added to permit reading all members.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +1. Click **Update policy**
```suggestion
1. Click **Update policy**.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +1. Click the **<RBAC** link in the upper left to return to the list of policies
```suggestion
1. Click the **RBAC** link to return to the list of policies.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +See the **Change a member's permissions** section in the [Members tutorial](members.md)
```suggestion
See the **Change a member's permissions** section in the [Members tutorial](members.md).
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +1. Click the **Remove** link to the right of the policy
```suggestion
1. Click the **Remove** link to the right of the policy.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +1. Click the **Remove** button in the prompt
```suggestion
1. Clickn**Remove** in the prompt.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +    > CAUTION: This will remove the policy
```suggestion
    > CAUTION: This will remove the policy.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +    > CAUTION: This will remove the policy
```suggestion
    > CAUTION: This will remove the policy.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/rbac.md
> +    > Note: you will not be able to remove the policy is applied to any team members.
```suggestion
    > Note: you will not be able to remove the policy that is applied to any team members.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +and enabling [Two-Factor Authentication](#two-factor-authentication)
```suggestion
and enabling [Two-Factor Authentication](#two-factor-authentication).
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +Learn how to enable strong passwords and enable Two-Factor Authentication
```suggestion
Learn how to enable strong passwords and enable Two-Factor Authentication.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Log into the [Vendor Portal](https://vendor.replicated.com), if prompted
```suggestion
1. Log into the [vendor portal](https://vendor.replicated.com).
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Navigate to the Team menu at the top right of the Vendor Portal
```suggestion
1. Navigate to the **Team** menu.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Click on the **Security** menu on the left
```suggestion
1. Click the **Security** menu.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +option enabled in your organization's Account Settings.
```suggestion
option enabled in your organization's account settings.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Click on the **account settings** link to be taken to the settings page
```suggestion
1. Click on the **account settings** link to be taken to the settings page.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Click the "Turn on Two-Factor Auth" button under the section titled
```suggestion
1. Under the **Two-factor authentication** section, click **Turn on Two-Factor Auth**.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Confirm your account password
```suggestion
1. Confirm your account password.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Follow the instructions on the screen to configure your 2FA device
```suggestion
1. Follow the instructions on the screen to configure your 2FA device.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +>Note:  If SAML authentication is configured for your team, Two-Factor Authentication will be bypassed. You can leave it enabled but you will not be prompted to enter a code when logging in.
```suggestion
>Note: If SAML authentication is configured for your team, Two-Factor Authentication will be bypassed. You can leave it enabled but you will not be prompted to enter a code when logging in.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +You can enforce strong passwords for all your team by requiring that all
```suggestion
You can enforce strong passwords for all members of your team by requiring that all
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Check the box next to "Require custom password complexity for team"
```suggestion
1. Check the box next to **Require custom password complexity for team**.
```

2021-11-11 05:07 UTC, samantha-replicated commented on content/vendor/guides/vendor-portal/team/security.md
> +1. Click "Save Changes"
```suggestion
1. Click **Save Changes**.
```

2022-03-07 21:14 UTC, jonquil2002 commented
@BarryWilliams Hey, Barry, I'm going to close this PR because the new docs site is launching and so many improvements have been made there that this is truly out-of-date. But, I know you put a lot of work into this PR, so if any of it is still relevant on the new site, I'd like to pair with you to make changes on the new site. All of the customer license content starts on this page on the new site: https://docs.replicated.com/vendor/releases-creating-customer

PTAL and let me know if changes are still needed to the new site. Thanks!

2022-03-07 21:14 UTC, closed without merging