Changed the Helm version and removed BETA
replicatedhq/kots.io pull request #617
Opened 2021-11-25 13:37 UTC by tdensmore

I would appreciate a technical review here - but as far as I know we are using Helm v3 be default, and it is no longer BETA.

2021-11-29 17:37 UTC, samantha-replicated submitted a review, later dismissed
LGTM! I'll defer to @morningvera to confirm technical accuracy before merging.

2021-11-29 18:07 UTC, morningvera approved these changes

2021-11-29 18:08 UTC, morningvera requested changes, later dismissed
just realized you changed the default. helm v2 has always been the default and changing it to v3 would be a breaking change so i suggest not editing that part.

2021-11-29 20:39 UTC, JustinN-Replicated commented
Agree with @morningvera that the 'default' we use hasn't been changed at all (at least for replicated helm install). Alluded to this in another file now also added to the pr.

2021-12-02 19:51 UTC, samantha-replicated commented on content/kots-cli/pull.md
> +| `--helm-version` | string | the Helm version with which to render the Helm Chart _(default `"v3"`)_. |
```suggestion
| `--helm-version` | string | the Helm version with which to render the Helm Chart _(default `"v2"`)_. |
```

2021-12-02 19:53 UTC, samantha-replicated commented
Ok, I just committed a change to ensure we were clear V2 is the default. Otherwise, it seems like we have ironed out everything in this PR? @tdensmore do you need one of us to merge for you?

2022-03-06 13:03 UTC, ajp-io commented
@JustinN-Replicated @tdensmore Can this be closed, merged, or updated and then merged?

2022-03-06 15:30 UTC, JustinN-Replicated commented
Not too sure why this wasn't merged back in December. @replicatedhq/replicated-docs  in case you wanted to take a look. I made some minor changes. @tdensmore if you could review that would be helpful too. Aside from that, lgtm

2022-03-06 19:59 UTC, tdensmore commented
Looks good to me. Can I ask why the default Helm install method is still `v2`? Helm 2 should never be used AFAIK...

2022-03-07 14:03 UTC, JustinN-Replicated commented
from Vera's comment above: https://github.com/replicatedhq/kots.io/pull/617#pullrequestreview-818144145

2022-03-07 14:04 UTC, JustinN-Replicated approved these changes

2022-03-07 21:24 UTC, jonquil2002 commented
@JustinN-Replicated Please lmk when we can close this and migrate the content diff to the new website. Trying to close out all of the PRs in this repo now. Thanks!

2022-03-07 23:59 UTC, JustinN-Replicated approved these changes

2022-03-08 00:19 UTC, JustinN-Replicated approved these changes

2022-03-08 00:20 UTC, merged

2022-03-08 00:20 UTC, JustinN-Replicated commented
@jonquil2002 all set